#ifndef _TIMER_CONFIG_H_
#define _TIMER_CONFIG_H_

#define TIME_DELAY 1000UL

#define TIMER0_ENABLE  ENABLE
#define TIMER1_ENABLE  ENABLE
#define TIMER2_ENABLE  ENABLE
#define TIMER_PRESCALLER DIV_BY_8
#define TIMER0_INTERRUPT_ENABLE ENABLE
#define TIMER1_INTERRUPT_ENABLE ENABLE
#define TIMER2_INTERRUPT_ENABLE ENABLE
#define TIMER0_MODE NORMAL


#endif
